// D language project BUILD file

target("d-hello") {
    type: executable;
    language: d;
    sources: ["hello.d"];
    flags: [
        "-O2",
        "-release",
        "-inline"
    ];
    output: "bin/d-hello";
}

